name: ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  SAM:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: go

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2 # https://github.com/aws-actions/setup-sam

      - name: Validate
        run: sam validate --debug --template-file template.yaml

      - name: Build
        run: sam build --use-container

  Go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout

      - name: Setup go
        uses: actions/setup-go@v3 # https://github.com/actions/setup-go
        with:
          go-version-file: 'lambda/go.mod'

      - name: Install dependencies
        run: go get -t -u -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3 # https://github.com/golangci/golangci-lint-action
        with:
          version: latest
          working-directory: lambda

      - name: Test
        run: go test -v ./...

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -v -o main
