name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # https://github.com/actions/checkout

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup SAM
      uses: aws-actions/setup-sam@v2 # https://github.com/aws-actions/setup-sam

    - name: Build
      run: sam build --use-container

    - name: Package
      run: sam package --s3-bucket ${{ secrets.S3_BUCKET }} --output-template-file ./packaged.yaml

    - name: Deploy
      run: |
        STACK_NAME=$(echo ${{ github.repository }} | sed -e 's#.*/##')
        sam deploy --stack-name $STACK_NAME \
          --template-file ./packaged.yaml \
          --s3-bucket ${{ secrets.S3_BUCKET }} \
          --parameter-overrides TwitterConsumerKey=${{ secrets.TWITTER_CONSUMER_KEY }} TwitterConsumerSecret=${{ secrets.TWITTER_CONSUMER_SECRET }} TwitterAccessToken=${{ secrets.TWITTER_ACCESS_TOKEN }} TwitterAccessSecret=${{ secrets.TWITTER_ACCESS_SECRET }} \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_IAM
